services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: plant_doctor
      POSTGRES_USER: plantdoctoradmin
      POSTGRES_PASSWORD: plantdoctoradminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    image: plant-doctor:latest
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_PLANTDOCTOR_URL: jdbc:postgresql://postgres:5432/plant_doctor
      SPRING_DATASOURCE_PLANTDOCTOR_USERNAME: plantdoctoradmin
      SPRING_DATASOURCE_PLANTDOCTOR_PASSWORD: plantdoctoradminpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: